### PR TITLE
WIP - Upgrade to React Native 0.64.1

### PR DESCRIPTION
**Pull request by ohrite**
XCode build errors out with the following message: 

Screen Shot 2021-05-12 at 23 20 51

### CODE REVIEW

**Comment by francisli** [comment]
The error you showed above is in a third-party library, react-native-gesture-handler. Upgrading the library to the latest version in package.json, then re-installing node modules and cocoapods fixes this issue.

More errors occur after this, however...

**Comment by francisli** [comment]
@ohrite I've now patched this branch such that it should now be possible to build and run the app in the iOS simulator. However, there are now errors in the running of the app, I suspect all the third-party libraries should be updated as well.

I also have not yet tested the Android build yet... however, hopefully this is a start that you or someone else can continue with?

**Comment by ohrite** [comment]
@francisli Awesome! We're back on track, and it looks like we've got a running iOS application. Android is now erroring out with the following RedBox message:

**Comment by francisli** [comment]
@ohrite just FYI, it appears that react-native-side-menu dependency has been forked and is being maintained here:

https://www.npmjs.com/package/react-native-side-menu-updated

**Comment by francisli** [comment]
@ohrite I'm marking this as ready for Review...

**Comment by francisli** [comment]
@ohrite in the interest of unblocking other folks from working on the app, I'm going to go ahead and merge this in now...

**Pull request merged**
