### PR TITLE
Changed several strings for the Spanish version of the App

### PR DESCRIPTION
**Pull request by santiagogomezl**
Found a few ways to restructure some sentences in order to improve readability.

### CODE REVIEW

**Comment by francisli** [comment]
@brittmj @ericaeilenberg do you want someone to review and approve these language translation suggestions, or should we go ahead and accept them and release a build with them?

**Comment by brittmj** [comment]
I believe @santiagogomezl was going to call out the changes he made in the translation Google Slides deck.  Erica wants the original Spanish translator to take a look at them before we finalize new language just to make sure everything stays accessible to the audience.  Santiago, let us know once you've had a change to make those comments.

**Comment by santiagogomezl** [comment]
@francisli @brittmj @ericaeilenberg I will review the doc and send over before next week's meeting.

**Comment by santiagogomezl** [comment]
Will make new pull request with agreed changes.

**Pull request closed without merging**
