### PR TITLE
User delete

### PR DESCRIPTION
**Pull request by markkhoo**
not sure what `ios/IntentionalWalkApp.xcodeproj/project.pbxproj` is

### CODE REVIEW

**Comment by francisli** [comment]
Wait a sec, didn't I just merge and delete this branch already?

I pushed up a few changes on my end after testing... ios/IntentionalWalkApp.xcodeproj/project.pbxproj is the iOS project file, which needed to be updated to support Apple M1 macs...

**Comment by markkhoo** [comment]
> 

Yes. There were translations that needed to be updated in `strings.js` that were discussed in the meeting after the previous pull request. Sorry for the confusion.

**Comment by francisli** [comment]
@markkhoo can you open a NEW PR just for these translation changes?

**Comment by markkhoo** [comment]
I opened a new one

**Pull request closed without merging**
