### PR TITLE
Signup

### PR DESCRIPTION
**Pull request by johnsonphan95**
User sign up flow

### CODE REVIEW

**Comment by francisli** [comment]
@johnsonphan95 hi johnson... because you're modifying the main App.js and introducing new dependencies, I'm going to go ahead and merge this in as it is so that we get those changes into the mainline before our different branches diverge significantly and it gets hard to reconcile...

If you're still working on things (i.e. putting content into scrollviews, etc) please rebase those additional changes onto a new branch off of master after I merge this PR.

We'll probably want to refactor the navigation stacks a bit after this to accommodate the main app... the main app screen should be the main stack, I think, and the sign-up flow should be opened as a modal on top of the main stack if it is detected that the app is running for the first time (i.e. there's no user account).

**Comment by francisli** [comment]
@johnsonphan95 any particular reason why you installed an older version of React Navigation (4.x) instead of the latest (5.x) that is featured on the website for the library...?

**Comment by johnsonphan95** [comment]
@francisli No particular reason for react navigation, just was trying to get something working from an old guide. I'll go ahead and see what I can do about refactoring the navigation as well, thanks for the feedback!

**Comment by francisli** [comment]
@johnsonphan95 actually, because I'm trying to integrate the Fitness API into a particular place in the flow, I'm currently working on refactoring things a bit.

For now, can you focus on improving the individual screens in the flow- ensuring the content is scrollable, so that things don't get cut off at the bottom, and that the buttons are in the appropriate place (right now they overlap the content when the screen is not log enough).

**Comment by francisli** [comment]
@johnsonphan95 I'll try to get my work merged in soon

**Comment by johnsonphan95** [comment]
@francisli yea of course no problem! Things have been a bit busy for me lately as well so no worries, I'll go ahead and do what I can for the time being!

**Pull request merged**
