### PR TITLE
[Fixes #258] Pin dependencies and patch build.gradle for Windows/Android

### LINKED ISSUE #258: Windows Setup Error
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-localization@1.0.15  
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from the root project      
npm WARN   13 more (@react-native-community/art, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.0.0 || ^15.6.0" from react-localization@1.0.15
npm WARN node_modules/react-localization
npm WARN   react-localization@"^1.0.14" from react-native-localization@2.1.6
npm WARN   node_modules/react-native-localization
npm WARN
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"^16.0.0 || ^15.6.0" from react-localization@1.0.15
npm WARN   node_modules/react-localization
npm WARN     react-localization@"^1.0.14" from react-native-localization@2.1.6
npm WARN     node_modules/react-native-localization
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: react-moment@0.9.7
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@"*" from @react-native-community/art@1.1.2
npm ERR!   node_modules/@react-native-community/art
npm ERR!     @react-native-community/art@"^1.0.3" from react-native-progress@4.0.3
npm ERR!     node_modules/react-native-progress
npm ERR!       react-native-progress@"^4.0.3" from the root project
npm ERR!   12 more (@react-native-community/masked-view, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.6.0 || ^16.0.0" from react-moment@0.9.7
npm ERR! node_modules/react-moment
npm ERR!   react-moment@"^0.9.7" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^15.6.0 || ^16.0.0" from react-moment@0.9.7
npm ERR!   node_modules/react-moment
npm ERR!     react-moment@"^0.9.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\Kimar\AppData\Local\npm-cache\_logs\2023-01-19T03_51_20_123Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kimar\AppData\Local\npm-cache\_logs\2023-01-19T03_51_20_123Z-debug-0.log

### PR DESCRIPTION
**Pull request by francisli**

### CODE REVIEW

**Comment by francisli** [comment]
@markkhoo see if this branch works for you...

For me, this compiles and launches in the Android emulator... the app then crashes, but I think that's a separate issue due to Node version incompatibility... going to test again after I downgrade from Node 18 to 16...

**Comment by markkhoo** [comment]
i'll give this branch a try

**Comment by markkhoo** [comment]
Progress! This compiles and launches in the Android emulator then crashes like you said. 

android_IW

**Comment by francisli** [comment]
OK, it's running for me now:

Screenshot_20230213_100110

**Comment by markkhoo** [comment]
wait what is different here?

**Comment by francisli** [comment]
@markkhoo what version of Node are you running? I un-installed Node 18, installed nvm for windows, and used it to install Node 16.19.0.

https://github.com/coreybutler/nvm-windows

**Comment by markkhoo** [comment]
Oh I got it to work! I forgot to use a new terminal.

**Comment by markkhoo** [comment]
Do we still want to attempt an upgrade?

**Comment by francisli** [comment]
@markkhoo at this point, we've spent enough time dealing with the build, that I'd recommend now working on actually prototyping/building the leaderboard...

Based on what I see with the changes in React 0.70, it might be a huge amount of work to upgrade to the latest version- some of the older, now-unmaintained libraries we use will have to be modified or replaced, etc...

**Pull request merged**
